name: scrape-new-grad
on:
  schedule:
    - cron: "0 * * * *"  # run hourly; adjust as you like
  workflow_dispatch: {}   # allow manual runs from the Actions tab

permissions:
  contents: write  # so we can commit updated seen.json

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python scraper.py

      - name: Commit seen.json (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update seen.json"
          file_pattern: seen.json
